apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kino
  name: kino
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kino
  template:
    metadata:
      labels:
        app: kino
    spec:
      containers:
      - name: kino
        image: registry.tino.sh/kino-app
        envFrom:
        - configMapRef:
            name: config
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: passwords
                key: MONGODB_URI
          - name: TMDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: passwords
                key: TMDB_API_KEY
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: passwords
                key: SECRET
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: passwords
                key: AUTH0_CLIENT_ID
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: passwords
                key: AUTH0_CLIENT_SECRET
          - name: AUTH0_ISSUER
            valueFrom:
              secretKeyRef:
                name: passwords
                key: AUTH0_ISSUER
        resources:
          requests:
            memory: "50Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      nodeSelector:
        arch: arm64
