---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-abaton
spec:
  schedule: "*/20 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kino-scraper
            image: registry.tino.sh/kino-scraper
            command: ["node", "abaton.js"]
            env:
              - name: MONGODB_DB
                value: "movie"
              - name: MONGODB_COLLECTION
                value: "movies"
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: MONGODB_URI
              - name: TMDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: TMDB_API_KEY
          restartPolicy: OnFailure

---          
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-dammtor
spec:
  schedule: "*/21 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kino-scraper
            image: registry.tino.sh/kino-scraper
            command: ["node", "dammtor.js"]
            env:
              - name: MONGODB_DB
                value: "movie"
              - name: MONGODB_COLLECTION
                value: "movies"
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: MONGODB_URI
              - name: TMDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: TMDB_API_KEY
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-netflix
spec:
  schedule: "*/22 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kino-scraper
            image: registry.tino.sh/kino-scraper
            command: ["node", "netflix.js"]
            env:
              - name: MONGODB_DB
                value: "movie"
              - name: MONGODB_COLLECTION
                value: "movies"
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: MONGODB_URI
              - name: TMDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: TMDB_API_KEY
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-netflix-kino-de
spec:
  schedule: "*/22 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kino-scraper
            image: registry.tino.sh/kino-scraper
            command: ["node", "netflix-kino-de.js"]
            env:
              - name: MONGODB_DB
                value: "movie"
              - name: MONGODB_COLLECTION
                value: "movies"
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: MONGODB_URI
              - name: TMDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: TMDB_API_KEY
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-amazon
spec:
  schedule: "*/23 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kino-scraper
            image: registry.tino.sh/kino-scraper
            command: ["node", "amazon.js"]
            env:
              - name: MONGODB_DB
                value: "movie"
              - name: MONGODB_COLLECTION
                value: "movies"
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: MONGODB_URI
              - name: TMDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: TMDB_API_KEY
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-amazon-kino-de
spec:
  schedule: "*/23 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kino-scraper
            image: registry.tino.sh/kino-scraper
            command: ["node", "amazon-kino-de.js"]
            env:
              - name: MONGODB_DB
                value: "movie"
              - name: MONGODB_COLLECTION
                value: "movies"
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: MONGODB_URI
              - name: TMDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: passwords
                    key: TMDB_API_KEY
          restartPolicy: OnFailure
