apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.tino.sh/kino
    context: ../../
    docker:
      target: kino
  - image: registry.tino.sh/scraper
    context: ../../
    docker:
      target: scraper
deploy:
  kustomize: {}
